### ISSUE TITLE
"cf cs" ERRORS

### ISSUE THREAD

**Issue by betht1220** [spring-cloud-samples/cloudfoundry-service-broker#15]
I have mongodb running at localhost:27017 and able to connect to it using robomongo.
Also, I deploy cloudfoundry-service-broker to CF and register this app as a mongo service broker.

"cf apps" returns
- mongodb-cf-service-broker   started           1/1         1G       1G     mongodb-cf-service-broker.myhost.com

After register with CF, "cf marketplace" returns 
- Mongo DB   Default Mongo Plan\*   A simple MongoDB service broker implementation

However, "cf cs "Mongo DB" "Default Mongo Plan" testMongodbInstance" returns follow ERROR

I've tried to look at this error for a while; but could not find out why. Command using curl to query for the broker's catalog is successful and return the catalog.
Any tips?
Thanks
Beth
--------ERROR--------
Server error, status code: 502, error code: 10001, message: Service broker error: Timed out after 10000 ms while waiting to connect. Client view of cluster state is {type=Unknown, servers=[{address=localhost:27017, type=Unknown, state=Connecting, exception={com.mongodb.MongoException$Network: Exception opening the socket}, caused by {java.net.ConnectException: Connection refused}}]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 10000 ms while waiting to connect. Client view of cluster state is {type=Unknown, servers=[{address=localhost:27017, type=Unknown, state=Connecting, exception={com.mongodb.MongoException$Network: Exception opening the socket}, caused by {java.net.ConnectException: Connection refused}}]

**Comment by scottfrederick** [comment]
The service broker running on CF must be able to talk to a MongoDB server. It won't be able to talk to the server on `localhost:27017` because the MongoDB server isn't running on the same `localhost` as the container the app is running in. You'll need to run the MongoDB server with a real hostname that the broker app can access.

**Comment by betht1220** [comment]
Scott - I have CF running on guest VM, and MongoDB runs on the host.  Will this setting work? If not, I can put MongoDB on a guest VM

**Comment by scottfrederick** [comment]
A `localhost` hostname isn't likely to work unless the service broker app and the MongoDb server are running on the same VM and in the same container. If you are pushing the broker app to CF, you can't make that happen since CF controls the container the broker app runs in. You need to configure the broker to look for the mongo server on a hostname other than `localhost`.
